version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./server/static:/usr/src/app/static
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: >
      bash -c "gunicorn config.wsgi -b 0.0.0.0:8000 -w 2"
    ports:
      - "8000:8000"
    expose:
      - "8000"
